<?php

namespace ContainerLUegYq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllergetProjectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wi6IlFE.App\Controller\ApiController::getProject()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wi6IlFE.App\\Controller\\ApiController::getProject()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'imageService' => ['privates', 'App\\Service\\ImageService', 'getImageServiceService', true],
            'repository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
        ], [
            'imageService' => 'App\\Service\\ImageService',
            'repository' => 'App\\Repository\\ProjectRepository',
        ]))->withContext('App\\Controller\\ApiController::getProject()', $container);
    }
}
