<?php

namespace ContainerLUegYq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCertificationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Certification' shared autowired service.
     *
     * @return \App\Entity\Certification
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Certification.php';

        return $container->privates['App\\Entity\\Certification'] = new \App\Entity\Certification();
    }
}
