<?php

namespace ContainerLUegYq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageControlleraddImageToTechnologyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oz6DqOo.App\Controller\ImageController::addImageToTechnology()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.oz6DqOo'] ?? $container->load('get_ServiceLocator_Oz6DqOoService'));

        if (isset($container->privates['.service_locator.oz6DqOo.App\\Controller\\ImageController::addImageToTechnology()'])) {
            return $container->privates['.service_locator.oz6DqOo.App\\Controller\\ImageController::addImageToTechnology()'];
        }

        return $container->privates['.service_locator.oz6DqOo.App\\Controller\\ImageController::addImageToTechnology()'] = $a->withContext('App\\Controller\\ImageController::addImageToTechnology()', $container);
    }
}
