<?php

namespace ContainerLUegYq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLastProjectTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\LastProjectType' shared autowired service.
     *
     * @return \App\Form\LastProjectType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/LastProjectType.php';

        return $container->privates['App\\Form\\LastProjectType'] = new \App\Form\LastProjectType();
    }
}
