<?php

namespace ContainerLUegYq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aGxXDNk.App\Controller\ProjectController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aGxXDNk.App\\Controller\\ProjectController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'projet' => ['privates', 'App\\Entity\\Project', 'getProjectService', true],
        ], [
            'manager' => '?',
            'projet' => 'App\\Entity\\Project',
        ]))->withContext('App\\Controller\\ProjectController::edit()', $container);
    }
}
