<?php

namespace ContainerLUegYq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQualityControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QldTEZN.App\Controller\QualityController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.QldTEZN'] ?? $container->load('get_ServiceLocator_QldTEZNService'));

        if (isset($container->privates['.service_locator.QldTEZN.App\\Controller\\QualityController::edit()'])) {
            return $container->privates['.service_locator.QldTEZN.App\\Controller\\QualityController::edit()'];
        }

        return $container->privates['.service_locator.QldTEZN.App\\Controller\\QualityController::edit()'] = $a->withContext('App\\Controller\\QualityController::edit()', $container);
    }
}
