<?php

namespace ContainerLUegYq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocialMediaControllerremoveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.itGDvuw.App\Controller\SocialMediaController::remove()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.itGDvuw.App\\Controller\\SocialMediaController::remove()'] = ($container->privates['.service_locator.itGDvuw'] ?? $container->load('get_ServiceLocator_ItGDvuwService'))->withContext('App\\Controller\\SocialMediaController::remove()', $container);
    }
}
