<?php

namespace ContainerLUegYq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTextControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FclEqdE.App\Controller\TextController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FclEqdE.App\\Controller\\TextController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'textRepository' => ['privates', 'App\\Repository\\TextRepository', 'getTextRepositoryService', true],
        ], [
            'manager' => '?',
            'textRepository' => 'App\\Repository\\TextRepository',
        ]))->withContext('App\\Controller\\TextController::new()', $container);
    }
}
