<?php

namespace ContainerLUegYq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTextControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p8xBh.H.App\Controller\TextController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p8xBh.H.App\\Controller\\TextController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'text' => ['privates', 'App\\Entity\\Text', 'getTextService', true],
        ], [
            'manager' => '?',
            'text' => 'App\\Entity\\Text',
        ]))->withContext('App\\Controller\\TextController::edit()', $container);
    }
}
