<?php

namespace ContainerUzrTEAH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllergetMediasService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xbu2uBN.App\Controller\ApiController::getMedias()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xbu2uBN.App\\Controller\\ApiController::getMedias()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'imageService' => ['privates', 'App\\Service\\ImageService', 'getImageServiceService', true],
            'repository' => ['privates', 'App\\Repository\\SocialMediaRepository', 'getSocialMediaRepositoryService', true],
        ], [
            'imageService' => 'App\\Service\\ImageService',
            'repository' => 'App\\Repository\\SocialMediaRepository',
        ]))->withContext('App\\Controller\\ApiController::getMedias()', $container);
    }
}
