<?php

namespace ContainerUzrTEAH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllergetQualitiesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YKwcIjC.App\Controller\ApiController::getQualities()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YKwcIjC.App\\Controller\\ApiController::getQualities()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\QualityRepository', 'getQualityRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\QualityRepository',
        ]))->withContext('App\\Controller\\ApiController::getQualities()', $container);
    }
}
