<?php

namespace ContainerUzrTEAH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllergetProjectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KsiLow..App\Controller\ApiController::getProject()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KsiLow..App\\Controller\\ApiController::getProject()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'datum' => ['privates', 'App\\Entity\\Project', 'getProjectService', true],
            'imageService' => ['privates', 'App\\Service\\ImageService', 'getImageServiceService', true],
        ], [
            'datum' => 'App\\Entity\\Project',
            'imageService' => 'App\\Service\\ImageService',
        ]))->withContext('App\\Controller\\ApiController::getProject()', $container);
    }
}
