<?php

namespace ContainerUzrTEAH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCertificationControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p9EULGF.App\Controller\CertificationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.p9EULGF'] ?? $container->load('get_ServiceLocator_P9EULGFService'));

        if (isset($container->privates['.service_locator.p9EULGF.App\\Controller\\CertificationController::edit()'])) {
            return $container->privates['.service_locator.p9EULGF.App\\Controller\\CertificationController::edit()'];
        }

        return $container->privates['.service_locator.p9EULGF.App\\Controller\\CertificationController::edit()'] = $a->withContext('App\\Controller\\CertificationController::edit()', $container);
    }
}
