<?php

namespace ContainerUzrTEAH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCertificationControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qXbY7S7.App\Controller\CertificationController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qXbY7S7.App\\Controller\\CertificationController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certificationRepository' => ['privates', 'App\\Repository\\CertificationRepository', 'getCertificationRepositoryService', true],
        ], [
            'certificationRepository' => 'App\\Repository\\CertificationRepository',
        ]))->withContext('App\\Controller\\CertificationController::show()', $container);
    }
}
