<?php

namespace ContainerUzrTEAH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCertificationControllerremoveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p9EULGF.App\Controller\CertificationController::remove()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p9EULGF.App\\Controller\\CertificationController::remove()'] = ($container->privates['.service_locator.p9EULGF'] ?? $container->load('get_ServiceLocator_P9EULGFService'))->withContext('App\\Controller\\CertificationController::remove()', $container);
    }
}
