<?php

namespace ContainerUzrTEAH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageControlleraddImageToMediaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.itGDvuw.App\Controller\ImageController::addImageToMedia()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.itGDvuw'] ?? $container->load('get_ServiceLocator_ItGDvuwService'));

        if (isset($container->privates['.service_locator.itGDvuw.App\\Controller\\ImageController::addImageToMedia()'])) {
            return $container->privates['.service_locator.itGDvuw.App\\Controller\\ImageController::addImageToMedia()'];
        }

        return $container->privates['.service_locator.itGDvuw.App\\Controller\\ImageController::addImageToMedia()'] = $a->withContext('App\\Controller\\ImageController::addImageToMedia()', $container);
    }
}
