<?php

namespace ContainerUzrTEAH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQualityControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RtAVg6a.App\Controller\QualityController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RtAVg6a.App\\Controller\\QualityController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'qualityRepository' => ['privates', 'App\\Repository\\QualityRepository', 'getQualityRepositoryService', true],
        ], [
            'qualityRepository' => 'App\\Repository\\QualityRepository',
        ]))->withContext('App\\Controller\\QualityController::index()', $container);
    }
}
