<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Image extends \App\Entity\Image implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imageFile' => [parent::class, 'imageFile', null],
        "\0".parent::class."\0".'imageName' => [parent::class, 'imageName', null],
        "\0".parent::class."\0".'imageSize' => [parent::class, 'imageSize', null],
        "\0".parent::class."\0".'projectt' => [parent::class, 'projectt', null],
        "\0".parent::class."\0".'socialMedia' => [parent::class, 'socialMedia', null],
        "\0".parent::class."\0".'technology' => [parent::class, 'technology', null],
        'id' => [parent::class, 'id', null],
        'imageFile' => [parent::class, 'imageFile', null],
        'imageName' => [parent::class, 'imageName', null],
        'imageSize' => [parent::class, 'imageSize', null],
        'projectt' => [parent::class, 'projectt', null],
        'socialMedia' => [parent::class, 'socialMedia', null],
        'technology' => [parent::class, 'technology', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
